### ISSUE TITLE
AutoGapple doesn work

### ISSUE THREAD

**Issue by Creper132** [CzechHek/Core#21]
AutoGapple doesn work i try this on redesky.com kokscraft.pl and singleplayer doesn work

**Comment by gabrielvicenteYT** [comment]
What liquidbounce version? b73 latest? or old b73? b72?

**Comment by Creper132** [comment]
b73 lasted

**Comment by Creper132** [comment]
but on b72 work
w

**Comment by CzechHek** [comment]
Cross-version is stupid and requires universal 1.8 and 1.12 arguments in LB functions, packets are wrapped and stuff, therefore it is not supported and it can't be.
