### ISSUE TITLE
TargetStrafe don't work (B73)

### ISSUE THREAD

**Issue by wephtz** [CzechHek/Core#24]
TargetStrafe doesn't work for me in b73 (i have core.lib)

**Comment by wephtz** [comment]
It's showing in movement but just doesn't strafe or do anything

**Comment by CzechHek** [comment]
Cross-version is stupid and requires universal 1.8 and 1.12 arguments in LB functions, packets are wrapped and stuff, therefore it is not supported and it can't be.
